<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hrs</string>
	</array>
	<key>name</key>
	<string>Higher-order Recursion Schemes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#gram</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#auto</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>auto</key>
		<dict>
			<key>begin</key>
			<string>(%BEGINA)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%ENDA)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#state</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.lustre</string>
		</dict>
		<key>gram</key>
		<dict>
			<key>begin</key>
			<string>(%BEGING)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%ENDG)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>nt_app</key>
		<dict>
			<key>begin</key>
			<string>\(([A-Z][a-zA-Z_0-9]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nt_app</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#t_app</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>([A-Z][a-zA-Z_0-9]*)((\s+[a-z][a-zA-Z_0-9]*)*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\.</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.lustre</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)\s*([A-Z][a-zA-Z_0-9]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.lustre</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)\s*([a-z][a-zA-Z_0-9]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.lustre</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nt_app</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#t_app</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>state</key>
		<dict>
			<key>begin</key>
			<string>([a-z][a-zA-Z_0-9]*)(\s+[a-z][a-zA-Z_0-9]*)\s*(-&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\.</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>nil</string>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</array>
		</dict>
		<key>t_app</key>
		<dict>
			<key>begin</key>
			<string>\(([a-z][a-zA-Z_0-9]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nt_app</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#t_app</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.hrs</string>
	<key>uuid</key>
	<string>3ab0d734-018a-46ad-bfaf-1d585250efd2</string>
</dict>
</plist>
