<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lus</string>
	</array>
	<key>name</key>
	<string>Lustre</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#externAnnotation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nodePref</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nodeRet</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#var</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#body</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typeDecl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#const</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>body</key>
		<dict>
			<key>begin</key>
			<string>\b(let)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(tel)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#equation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#internAnnotation</string>
				</dict>
			</array>
		</dict>
		<key>boolCst</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.other.lustre</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--.*</string>
					<key>name</key>
					<string>comment.lustre</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(\*</string>
					<key>end</key>
					<string>\*\)</string>
					<key>name</key>
					<string>comment.lustre</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>const</key>
		<dict>
			<key>begin</key>
			<string>const\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>=</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>constKey</key>
		<dict>
			<key>match</key>
			<string>\bconst\b</string>
			<key>name</key>
			<string>keyword.lustre</string>
		</dict>
		<key>contractMode</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--@)(mode)\s*(\w+)\s*(;)</string>
		</dict>
		<key>contractStmt</key>
		<dict>
			<key>begin</key>
			<string>(--@)(require|ensure)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>cst</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#floatCst</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#intCst</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolCst</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stringCst</string>
				</dict>
			</array>
		</dict>
		<key>equation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\w+)\s*=</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Regular ident lhs.</string>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\((\w+\s*[,\s*\w+\s*]*)\)\s*=</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Parenthesized tuple equation.</string>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+\s*[,\s*\w+\s*]*)\s*=</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Unparenthesized tuple equation.</string>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)\s*((\[\s*[^\]]+\s*\]\s*)+)=</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Array thing.</string>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Keywords</string>
					<key>match</key>
					<string>\b(if|then|else|not|and|or|pre|fby)\b</string>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>-&gt; keyword (no \b delimiter)</string>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Operators</string>
					<key>match</key>
					<string>&lt;&gt;|=|&gt;=|&gt;|&lt;=|&lt;|\+|\-|\*|/|%</string>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cst</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+\s*\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Node / function call</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Idents</string>
					<key>match</key>
					<string>\b\w+\b</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Array</string>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Struct</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\w+\s*(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.other.lustre</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(;|(?=}))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>externAnnotation</key>
		<dict>
			<key>comment</key>
			<string>Annotations outside bodies.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inContract</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ghostVar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#contractMode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#contractStmt</string>
				</dict>
			</array>
		</dict>
		<key>floatCst</key>
		<dict>
			<key>match</key>
			<string>\b\s*([0-9]+\.[0-9]*)\b</string>
			<key>name</key>
			<string>constant.other.lustre</string>
		</dict>
		<key>ghostVar</key>
		<dict>
			<key>begin</key>
			<string>(--@)(var|const)\s*(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>=</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>inContrMode</key>
		<dict>
			<key>begin</key>
			<string>(mode)\s*(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>when\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>When clause</string>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inContrWhenExpr</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Actual contract</string>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inContrStmt</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>inContrOpts</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>exhaustive|exclusive</string>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
			</array>
		</dict>
		<key>inContrStmt</key>
		<dict>
			<key>begin</key>
			<string>(require|ensure)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>inContrVar</key>
		<dict>
			<key>begin</key>
			<string>(var|const)\s*(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>=</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>inContrWhenExpr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inContrWhenExpr</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Bool operators</string>
					<key>match</key>
					<string>(not|and|or)\b|=&gt;</string>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Ident correspending to another mode</string>
					<key>match</key>
					<string>\w+</string>
				</dict>
			</array>
		</dict>
		<key>inContract</key>
		<dict>
			<key>begin</key>
			<string>(\(\*@)(contract)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\*\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inContrOpts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inContrVar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inContrMode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inContrStmt</string>
				</dict>
			</array>
		</dict>
		<key>include</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(include)\s+(\"[a-zA-Z][a-zA-Z_\-\.]*\")</string>
		</dict>
		<key>intCst</key>
		<dict>
			<key>match</key>
			<string>\b\s*(0|[1-9][0-9]*)\b</string>
			<key>name</key>
			<string>constant.other.lustre</string>
		</dict>
		<key>internAnnotation</key>
		<dict>
			<key>comment</key>
			<string>Annotations inside bodies.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lustrecOrKind2</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>[.]</string>
			<key>name</key>
			<string>invalid.lustre</string>
		</dict>
		<key>lustrecOrKind2</key>
		<dict>
			<key>begin</key>
			<string>(--[!|%])(\w+)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>nodePref</key>
		<dict>
			<key>begin</key>
			<string>\b(node|function)\s+(\w+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.lustre</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>More precisely, a node or a function prefix.</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Type for an input.</string>
					<key>end</key>
					<string>(;|(?=\)))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#constKey</string>
				</dict>
			</array>
		</dict>
		<key>nodeRet</key>
		<dict>
			<key>begin</key>
			<string>(returns)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))\s*(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Type for an output.</string>
					<key>end</key>
					<string>(;|(?=\)))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>stringCst</key>
		<dict>
			<key>match</key>
			<string>\"[^\"]*\"</string>
			<key>name</key>
			<string>constant.other.lustre</string>
		</dict>
		<key>structField</key>
		<dict>
			<key>begin</key>
			<string>(\w+)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;|(?=}))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Primitive types.</string>
					<key>match</key>
					<string>\b(bool|int|real)\b</string>
					<key>name</key>
					<string>support.type.lustre</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(subrange)\s*\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Subranges.</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>constant.numeric.lustre</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#intCst</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Tuples.</string>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Arrays.</string>
					<key>match</key>
					<string>(\w+)?(\^)(\w+|[1-9]\d*)</string>
					<key>name</key>
					<string>support.type.lustre</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>User-defined type.</string>
					<key>match</key>
					<string>\w+</string>
				</dict>
			</array>
		</dict>
		<key>typeDecl</key>
		<dict>
			<key>begin</key>
			<string>(type)\s+(\w+)\s*=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeDeclRhs</string>
				</dict>
			</array>
		</dict>
		<key>typeDeclRhs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Struct.</string>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#structField</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var</key>
		<dict>
			<key>begin</key>
			<string>\b(var)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.lustre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(let))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.lustre</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lus</string>
	<key>uuid</key>
	<string>23a435f9-1904-4b91-99ee-7609e0e45879</string>
</dict>
</plist>
